/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

/**
 *
 * @author WIN 11
 */
public class signUp extends javax.swing.JFrame {

    /**
     * Creates new form signUp
     */
    public static String nama;
    public static String username;
    public static String password;
    public static String kpassword;
    
    public signUp() {
        initComponents();
        setVisible(true);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        PKUp = new javax.swing.JPanel();
        PBUp = new javax.swing.JPanel();
        judulSU = new javax.swing.JLabel();
        namaLbl = new javax.swing.JLabel();
        namaTextSU = new javax.swing.JTextField();
        unameLbl = new javax.swing.JLabel();
        unameTextSU = new javax.swing.JTextField();
        pswdLbl = new javax.swing.JLabel();
        kpswdSU1 = new javax.swing.JLabel();
        pswdfieldSU = new javax.swing.JPasswordField();
        kpswdfieldSU = new javax.swing.JPasswordField();
        registerBtn = new javax.swing.JButton();
        validasi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PKUp.setBackground(new java.awt.Color(242, 165, 200));
        PKUp.setPreferredSize(new java.awt.Dimension(460, 40));

        javax.swing.GroupLayout PKUpLayout = new javax.swing.GroupLayout(PKUp);
        PKUp.setLayout(PKUpLayout);
        PKUpLayout.setHorizontalGroup(
            PKUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        PKUpLayout.setVerticalGroup(
            PKUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        PBUp.setBackground(new java.awt.Color(242, 199, 232));
        PBUp.setMinimumSize(new java.awt.Dimension(0, 0));
        PBUp.setPreferredSize(new java.awt.Dimension(460, 360));

        judulSU.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        judulSU.setText("WEEMTIX");

        namaLbl.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        namaLbl.setText("Nama");

        namaTextSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextSUActionPerformed(evt);
            }
        });

        unameLbl.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        unameLbl.setText("Username");

        pswdLbl.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        pswdLbl.setText("Password");

        kpswdSU1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        kpswdSU1.setText("Konfirmasi Password");

        pswdfieldSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdfieldSUActionPerformed(evt);
            }
        });

        registerBtn.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        validasi.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout PBUpLayout = new javax.swing.GroupLayout(PBUp);
        PBUp.setLayout(PBUpLayout);
        PBUpLayout.setHorizontalGroup(
            PBUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PBUpLayout.createSequentialGroup()
                .addGroup(PBUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PBUpLayout.createSequentialGroup()
                        .addGroup(PBUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PBUpLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(PBUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaLbl)
                                    .addComponent(unameLbl)
                                    .addComponent(pswdLbl)))
                            .addGroup(PBUpLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(kpswdSU1)))
                        .addGap(28, 28, 28)
                        .addGroup(PBUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PBUpLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(PBUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(unameTextSU, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(namaTextSU, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))
                            .addGroup(PBUpLayout.createSequentialGroup()
                                .addGroup(PBUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(registerBtn)
                                    .addGroup(PBUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pswdfieldSU, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                        .addComponent(kpswdfieldSU)
                                        .addComponent(validasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PBUpLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(judulSU)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        PBUpLayout.setVerticalGroup(
            PBUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBUpLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(judulSU)
                .addGap(18, 18, 18)
                .addGroup(PBUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLbl)
                    .addComponent(namaTextSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PBUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unameLbl)
                    .addComponent(unameTextSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PBUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pswdLbl)
                    .addGroup(PBUpLayout.createSequentialGroup()
                        .addComponent(pswdfieldSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PBUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kpswdfieldSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kpswdSU1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validasi, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerBtn)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PKUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(PBUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PKUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PBUp, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaTextSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextSUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextSUActionPerformed

    private void pswdfieldSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdfieldSUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdfieldSUActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        if(kpswdfieldSU.getText().equals(pswdfieldSU.getText())){
            nama = namaTextSU.getText();
            username = unameTextSU.getText();
            password = kpswdSU1.getText();
            
            //go to login
            Login lg = new Login();
            lg.setVisible(true);
            lg.pack();
            lg.setLocationRelativeTo(null);
            lg.setDefaultCloseOperation(signUp.EXIT_ON_CLOSE);
            this.setVisible(false);
        }else{
            validasi.setText("The Password doesn't match");
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PBUp;
    private javax.swing.JPanel PKUp;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel judulSU;
    private javax.swing.JLabel kpswdSU1;
    private javax.swing.JPasswordField kpswdfieldSU;
    private javax.swing.JLabel namaLbl;
    private javax.swing.JTextField namaTextSU;
    private javax.swing.JLabel pswdLbl;
    private javax.swing.JPasswordField pswdfieldSU;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel unameLbl;
    private javax.swing.JTextField unameTextSU;
    private javax.swing.JLabel validasi;
    // End of variables declaration//GEN-END:variables
}
